# Generated by Django 4.1.4 on 2022-12-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_todoyellow_todored_todogreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeHighcore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
